### PR TITLE
 update API finished

### PR DESCRIPTION
**Pull request by Sijia-Hao1998**

### CODE REVIEW

**Comment by phuang07** [comment]
There's currently no test case created for this API. Please add test case. Thanks.

**Comment by Sijia-Hao1998** [comment]
> There's currently no test case created for this API. Please add test case. Thanks.

Not really sure how to do that. Can someone help me with that ?

**Comment by ShreyRupani** [comment]
Let's hop on a call after the exam and do the tests together.
Paired programming style.

**Comment by phuang07** [comment]
Already resolved.

**Pull request closed without merging**
